---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: content/design
  label: Design
  create: all
  match: "**/*"
- type: directory
  path: content/thankyou
  label: Thankyou
  create: all
  match: "**/*"
- type: directory
  path: content/life
  label: Life
  create: all
  match: "**/*"
- type: directory
  path: content/coding
  label: Coding
  create: all
  match: "**/*"
- type: directory
  path: content/youngmangame
  label: Youngmangame
  create: all
  match: "**/*"
- type: directory
  path: content/article
  label: Article
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.48'
